name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgelesssys/edgelessrt-dev:ci
    steps:

    - name: Checkout edgelessrt
      uses: actions/checkout@v2
      with:
        submodules: true
        path: edgelessrt

    - name: Setup directories
      run: |
        mkdir edgelessrt/build

    - name: Build edgelessrt
      run: |
        cmake -GNinja ..
        ninja
      working-directory: edgelessrt/build

    - name: Test edgelessrt
      run: |
        OE_SIMULATION=1 ctest --output-on-failure -E tests/crypto/
      working-directory: edgelessrt/build

    - name: CPack
      run: cpack -G DEB
      working-directory: edgelessrt/build

    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: edgelessrt
        path: edgelessrt/build/*.deb
